### ISSUE TITLE
[repo-dirty-checker] Pridať support pre config file

### ISSUE THREAD

**Issue by adam-dej** [trojsten/sysadmin-script-collection#2]
Je potrebné pridať support pre config file to `repo-dirty-checker`, bolo by dobré mať support pre viacero varovaní jedného typu (príklad: prvé varovanie 10 po spustení, každé ďalšie vzdy po 5) a support pre viacero foldrov. Config file by mal sídliť v `/usr/local/etc/repo-dirty-checker.conf` a nastavuje sa v ňom:
- zoznam watchovaných foldrov (default `/etc /usr/local/etc`)
- ~~počet verbálnych varovaní ktoré sa majú zobraziť~~
- čas od zdetekovania bordelu po prvé verbálne varovanie (default `30`)
- čas medzi verbálnymi varovaniami (default `10`)
- čas od zdetekovania bordelu po prvé mailové varovanie (default `60`)
- čas medzi mailovými varovaniami (default `90`)

Note:
časom myslim počet spustení scriptu cronom

**Comment by lubo** [comment]
Mam pre kazdy folder samostatne trackovat cas a userov ?

**Comment by adam-dej** [comment]
Yes, please. Mohom by si potom (ak by si si nepamatal foldre, resp cas foldrov) nerozoznat situaciu kedy je v jednom foldri bordel, medzi spusteniami niekto uprace a hned stihne spravit bordel v druhej zlozke.
Userov ani nemusis, ale cas kolko je tam bordel by bolo dobre.

**Comment by lubo** [comment]
Počet verbálnych varovaní ktoré sa majú zobraziť ma byt maximalny pocet varovani, ktore sa zobrazia ?

**Comment by adam-dej** [comment]
Hmm... mas pravdu, to je blbost. Verbalne varovania by sa mali zobrazovat +- stale s rozumnym delayom. Takze ignoruj parametr "pocet verbalnych varovani ktore sa maju zobrazit" a zobrazuj ich, kym je bordel.

**Comment by lubo** [comment]
Dobre. Ake chcem defaultne hodnoty ?

**Comment by adam-dej** [comment]
Pridané do popisu issue
