### ISSUE TITLE
Inštalácia týchto scriptov

### ISSUE THREAD

**Issue by adam-dej** [trojsten/sysadmin-script-collection#3]
Treba spravit port ktorý nainštaluje tieto scripty, vie ich upgradovať a aj cleanly odinštalovať.
### OLD:

Tieto scripty plánujeme inštalovať do `/root/bin`. Config súbory treba prekopírovať tam kde majú byť.

Inštalácia by mala symlinknúť všetky relevantné scripty do `/root/bin`. Keďže explicit is better than implicit treba vytvoriť v repe nejaký folder `bin/` a script ktorý obsahuje symlinky na scirpty ktoré chceme nainštalovať. Rovnako aj `config/` ktorého obsah sa prekopíruje (ak ešte neexistuje) do `/usr/local/etc`.

Treba vytvoriť túto štruktúru v repozitári a scripty `install` a `uninstall` v top-leveli.

**Comment by lubo** [comment]
1. Preco `/root/bin` a nie `/usr/local/bin` ?
2. Preco radsej nevytvarat package pre podporovane systemy ?

**Comment by adam-dej** [comment]
S Kamilou sme sa rozprávali, a povedala že custom port (spôsob inštalovania sw zo source vo FreeBSD) je na toto overkill. Keď nie je port, nechcem šahať do `/usr/loca/bin`. Osobne však niesom striktne proti (a napísať taký port je vraj triviálne rýchle, možno som dokonca _jemne_ za), nech sa @AnotherKamila vyjadrí.

**Comment by lubo** [comment]
Ak sa to da spravit relativne rychlo (comu urcite verim), tak ja som jednoznacne za a ak to nikto iny nespravi, tak ja mozem.

**Comment by adam-dej** [comment]
Tak teda sprav, myslim ze bude fajn ked to bude.

Dik. Zeditujem top-level post.

**Comment by AnotherKamila** [comment]
Vzhľadom na to, že toho nakoniec asi bude trocha viac, ako som si pôvodne myslela, custom port je možno predsalen dobrý. Môžem spraviť, alebo ak sa niekto chcete pohrať, môžte spraviť. Podľa mňa je fajn odpísať ten z `/usr/ports/sysutils/tarsnap-backup`, keďže inštalácia tohto je dosť to isté.

**Comment by lubo** [comment]
Nuz, chceme mat Makefile a dalsie subory v roote tohto repa alebo v inom repe ?

@AnotherKamila Nevidim `/usr/ports/sysutils/tarsnap-backup` na proto-inteligentovi, treba nechat zbehnut nejaky update ?

**Comment by adam-dej** [comment]
Custom repo iba pre port(y) (ak budeme robit aj dalsie veci), zdrojaky ma stiahnut Makefile.

Na inteligentovi treba spustit `portsnap fetch install`.

**Comment by adam-dej** [comment]
https://github.com/trojsten/freebsd-custom-ports, done.
