### ISSUE TITLE
[properly] by sa mal správať trochu inak vnútri jailu ako na bare železe

### ISSUE THREAD

**Issue by adam-dej** [trojsten/sysadmin-script-collection#4]
Konkrétne spôsob robenia snapshotov vnútri jailu je odlišný od snapshotovania systému na bare železe. Treba podporovať oba a mať nejaký field v configu ktorý hovorí o tom ktorý použiť.

**Comment by AnotherKamila** [comment]
`make_snapshot` fcia,  ako `run_git`,  napríklad.
