### ISSUE TITLE
[setup-log] treba napísať

### ISSUE THREAD

**Issue by adam-dej** [trojsten/sysadmin-script-collection#5]
# Treba naimplementovať `setup-log`
## Čo to má byť?

`setup-log` má byť jeden z helper scriptov, ktorý slúži na automatizáciu vkladania záznamov do našich setup logov.

Keďže napísať niečo takéto v shelli by (síce bolo možné, ale určite by to) bol PITA, navrhujem použiť python.
## Usage

`setup-log [--config config] [-l logfile] [-t new_title [-d date]] [-c used_command] message...`
- `--config config`: Lokácia config súboru. Default `/usr/loca/etc/trojsten-log.conf`
- `-l logfile`: Log file do ktorého sa má písať. Default hodnota je z configu.
- `-t new_title`: Vytvoriť v logu nový tématicky nadpis a message vloží pod neho (inak vloží do posledného tématického nadpisu)
- `-d YYYY-mm-dd`: Použiť tento dátum v tématickom nadpise, nie aktuálny
- `-c used_command`: Ak je správa o príkaze, ktorý sa použil, tu je ten príkaz
## Log format

Naše logy sú markdownové súbory s nasledovným formátom:

```
randomserver setup log
======================

<!-- begin setup log -->

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```

Hlavný nadpis sa nikdy nemení. V skutočnosti skript má ignorovať (a nepokaziť!) to, čo je nad markerom a skript to zaujíma od neho (ostro) nižšie. Nadpisy topicu hovoria o logických celkoch setupu, ktoré sa na servri diali (napríklad "Setup nginx with SSL"). Najnovší nadpis topicu je pri vrchu logu. Pod týmto nadpisom sú správy samotné. Ak je k správe asociovaný nejaký príkaz, tak ten je ako subbullet a v backtickoch.
### (skoro) bez parametrov

`setup-log  -c 'rm -rf /' 'Celé to zapálim!'`

pridá správu ako nový (=> posledný) bullet point pod najnovší nadpis. Ak je v poslednom nadpise dátum iný ako momentálny, vypíše varovanie, ale pokračuje.

```
randomserver setup log
======================

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`
  * Celé to zapálim!
    * `rm -rf /`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```
### s parametrom `-t`

`setup-log -t "Network config" "Start setting up the network"`

Vytvorí nový nadpis (s aktuálnym dátumom) a pridá nadpis pod neho.

```
randomserver setup log
======================

Network config (2017-03-11)
-------------------------

  * Start setting up the network

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```
## Config

Defaultné umiestnenie configu je v `/usr/local/etc/setup_log.conf`. Rozhodne tam je parameter `setup_log_path` -- umiestnenie logfile-u a parameter `log_marker` -- tvar markera (napr. s hodnotou `"<!-- begin setup log -->"`) Ak sa počas vývoja vyskytnú ďalšie veci, ktoré by možno bolo dobré dať do configu, kľudne.
## OLD, IGNORE:

```
# Treba naimplementovať `log`

## Čo to má byť?

`log` má byť jeden z helper scriptov ktorý slúži na automatizáciu vkladania záznamov do naších setup logov.

Keďže napísať niečo takéto v shelli by (síce bolo možné, ale určite by to) bol PITA, navrhujem použiť python.

## Usage

`log [--config config] [-l logfile] [-t new_title [-d date]] [--last-title] message [-c used_command]`

  * `--config config`: Lokácia config súboru. Default `/usr/loca/etc/trojsten-log.conf`
  * `-l logfile`: Log file do ktorého sa má písať. Default hodnota je z configu.
  * `-t new_title`: Vytvoriť v logu nový tématicky nadpis a message vloží pod neho
  * `-d date`: Použiť tento dátum v tématickom nadpise, nie aktuálny
  * `--last-title`: Túto správu vložiť do posledného tématického nadpisu
  * `-c used_command`: Ak je správa o príkaze ktorý sa použil, tu je ten príkaz

## Log format

Naše logy sú markdownové súbory s nasledovným formátom:

``
randomserver setup log
======================

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
``

Hlavný nadpis sa nikdy nemení. Nadpisy topicu hovoria o logických celkoch setupu ktoré sa na servri diali (napríklad "Setup nginx with SSL"). Najnovší nadpis topicu je pri vrchu logu. Pod týmto nadpisom sú správy samotné. Ak je k správe asociovaný nejaký príkaz, tak ten je ako subbullet a v backtickoch.

## Behaviour

### (skoro) bez parametrov

`log "Celé to zapálim!" -c "rm -rf /"`

pridá správu pod hlavný nadpis:

``
randomserver setup log
======================

  * Celé to zapáliť (2017-03-11)
    * `rm -rf /`

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
``


### s parametrom `-t`

`log -t "Network config" "Start setting up the network"`

Vytvorí nový nadpis a pridá nadpis pod neho.

``
randomserver setup log
======================

Network config (2017-03-11)
-------------------------

  * Start setting up the network

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
``

### s parametrom `--last-title`

`log --last-title "Configure network params"`

Nájde posledný nadpis, nájde posledný bullet point pod tým nadpisom, a pridá pod neho.

``
randomserver setup log
======================

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`
  * Configure network params

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
``

## Config

Defaultné umiestnenie configu je v `/usr/local/etc/trojsten-log.conf`. Rozhodne tam je parameter umiestnenia logfile-u. Pravdepodobne tam môže byť parameter ktorý hovorí o formáte logfile-u. Ak sa počas vývoja vyskytnú ďalšie veci, ktoré by možno bolo dobré dať do configu, kľudne.
```

**Comment by AnotherKamila** [comment]
Čo by som zmenila:
- urvať explicitný `--last-title` a spraviť toto default behavior; úplne urvať správanie "napísať čosi bez nadpisu" (veci majú mať nadpis)
- názov: premenovať na `setup_log`, lebo `log` nie je dosť špecifické
- miesto nejakej blbosti typu "preskoč prvé 2 riadky a potom píš" zaviesť explicitný marker v tom súbore, takže potom správanie bude bude "toto nájdi a píš pod to" -- menej error-prone, explicit is better than implicit a tak
- default miesto pre config `$PREFIX/etc/setup_log.conf`, nie `trojsten-log.conf`

---

Zeditovaná verzia by potom bola:

# Treba naimplementovať `setup_log`

## Čo to má byť?

`setup_log` má byť jeden z helper scriptov, ktorý slúži na automatizáciu vkladania záznamov do našich setup logov.

Keďže napísať niečo takéto v shelli by (síce bolo možné, ale určite by to) bol PITA, navrhujem použiť python.

## Usage

`log [--config config] [-l logfile] [-t new_title [-d date]] [-c used_command] message...`
- `--config config`: Lokácia config súboru. Default `/usr/loca/etc/trojsten-log.conf`
- `-l logfile`: Log file do ktorého sa má písať. Default hodnota je z configu.
- `-t new_title`: Vytvoriť v logu nový tématicky nadpis a message vloží pod neho (inak vloží do posledného tématického nadpisu)
- `-d YYYY-mm-dd`: Použiť tento dátum v tématickom nadpise, nie aktuálny
- `-c used_command`: Ak je správa o príkaze, ktorý sa použil, tu je ten príkaz

## Log format

Naše logy sú markdownové súbory s nasledovným formátom:

```
randomserver setup log
======================

<!-- begin setup log -->

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```

Hlavný nadpis sa nikdy nemení. V skutočnosti skript má ignorovať (a nepokaziť!) to, čo je nad markerom a skript to zaujíma od neho (ostro) nižšie. Nadpisy topicu hovoria o logických celkoch setupu, ktoré sa na servri diali (napríklad "Setup nginx with SSL"). Najnovší nadpis topicu je pri vrchu logu. Pod týmto nadpisom sú správy samotné. Ak je k správe asociovaný nejaký príkaz, tak ten je ako subbullet a v backtickoch.

## Behaviour

### (skoro) bez parametrov

`log 'Celé to zapálim!' -c 'rm -rf /'

pridá správu ako nový (=> posledný) bullet point pod najnovší nadpis:

```
randomserver setup log
======================

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`
  * Celé to zapálim!
    * `rm -rf /`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```

### s parametrom `-t`

`log -t "Network config" "Start setting up the network"`

Vytvorí nový nadpis (s aktuálnym dátumom) a pridá nadpis pod neho.

```
randomserver setup log
======================

Network config (2017-03-11)
-------------------------

  * Start setting up the network

Nadpis topicu (2016-03-11)
--------------------------

  * Message 1
  * Message 2
  * Message 3
    * `command_for_message 3`

Nadpis staršieho topicu (2013-03-11)
------------------------------------

  * Message 1
  * Message 2
```

## Config

Defaultné umiestnenie configu je v `/usr/local/etc/setup_log.conf`. Rozhodne tam je parameter `setup_log_path` -- umiestnenie logfile-u a parameter `log_marker` -- tvar markera (napr. s hodnotou `"<!-- begin setup log -->"`) Ak sa počas vývoja vyskytnú ďalšie veci, ktoré by možno bolo dobré dať do configu, kľudne.

**Comment by adam-dej** [comment]
OK, principiálne súhlasím. Last title ako default behaviour je tiež OK, ale zdá sa mi, že je jednoduché zabudnúť povedať mu nech vytvorí nový new title. Možno warning (nekritický) ak dátum v nadpise nesedí s dnešným?

**Comment by AnotherKamila** [comment]
Warning môže byť.

**Comment by adam-dej** [comment]
OK, zeditujem issue s novou speckou + warning

**Comment by AnotherKamila** [comment]
Aaaaaaaaaaaa podstatná vec, na ktorú som zabudla: všetky options musia ísť pred samotný message, a ako message sa má použiť všetky zvyšné argumenty, nie iba jeden -- tak ako to mám v `properly`. Dôvod: nikomu sa nechce písať úvodzovky. Takže použitie potom bude `setup_log -t 'make it awesome' -c 'portmaster something/awesome' install something awesome, because it is awesome`.

**Comment by adam-dej** [comment]
Beriem, ale úvodzovky budem stále vrelo odporúčať, chcem sa vyhnúť unexpected shell expansions :D

**Comment by AnotherKamila** [comment]
Samozrejme. Na druhej strane ak som si istá, že sa nič zaujímavé nestane,
bola by to zbytočne otrava.

**Comment by ivan-lattak** [comment]
napísal som (de1c78a8cfb5c0821cdd68d19a9d7eeb4340f2ec), ale nemal som ako otestovať, prípadné chyby mi vypichni, opravím
